version: '3.8'
services:
  api-gateway:
    image: cevheri/api-gateway
    container_name: api-gateway
    hostname: api-gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
    ports:
    - 9191:9191