#global:
#  scrape_interval: 15s

#scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#
#    static_configs:
#      - targets: [ 'localhost:9090' ]
#
#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ 'localhost:8080' ]
    # docker pull prom/prometheus
    # docker run -d -p 9090:9090 -v <PATH_TO_prometheus.yml_FILE>:/etc/prometheus/prometheus.yml prom/prometheus
    # docker run -d -p 3000:3000 grafana/grafana